WebUI/Twitter.WebUI.Site/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Twitter.Data;
using Twitter.WebUI.Site.Models;

namespace Twitter.WebUI.Site.Controllers
{
    public class ListController : Controller
    {
        ListData _listData;
        PopularUserData _popularUserData;

        public ListController()
        {
            _listData = new ListData();
            _popularUserData = new PopularUserData();
        }

        public ActionResult Index(string slug)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { e = "list-name-empty" });

            var item = _listData.GetBy(x => x.Slug == slug).FirstOrDefault();
            if (item == null)
                return RedirectToAction("Index", "Home", new { e = "not-found-list" });


            Random rnd = new Random();

            var randomLists = _listData.GetBy(x => x.IsActive).OrderBy(x => rnd.Next()).Take(3).ToList();

            var users = _popularUserData.GetBy(x => x.ListId == item.Id && x.IsActive).OrderByDescending(x=>x.FollowerCount).ToList();

            var model = new ListViewModel()
            {
                List = item,
                Lists = randomLists,
                PopularUser = users,
            };

            return View(model);
        }

        public ActionResult All()
        {
            var lists = _listData.GetBy(x => x.IsActive);

            var model = new ListViewModel()
            {
                List = null,
                Lists = lists,
                PopularUser = null,
            };

            return View(model);
        }
    }
}

WebUI/Twitter.WebUI.Site/Controllers/SearchController.cs
namespace Twitter.WebUI.Site.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Twitter.Api;
    using Twitter.Data;
    using Twitter.WebUI.Site.Models;

    public class SearchController : Controller
    {
        AuthUserData _userData;
        TokenData _tokenData;
        PopularUserData _popularUserData;

        public SearchController()
        {
            _userData = new AuthUserData();
            _tokenData = new TokenData();
            _popularUserData = new PopularUserData();
        }

        public ActionResult Index(string param)
        {
            var model = new SearchViewModel();

            if (string.IsNullOrEmpty(param))
                return View(model);

            Random rnd = new Random();
            var userById = _userData.GetBy(x => x.IsActive).OrderBy(x => rnd.Next()).FirstOrDefault();
            var token = _tokenData.GetByKey(userById.TokenId);

            var info = new Gatherer(token.ConsumerKey, token.ConsumerSecret, userById.OAuthToken, userById.OAuthTokenSecret);

            var searchUser = info.GetUsersSearch(param);

            if (searchUser.Users.Count() <= 0)
            {
                model.Populars = _popularUserData.GetBy(x => x.IsActive).OrderBy(x => rnd.Next()).Take(20).ToList();
            }

            model = new SearchViewModel()
            {
                Users = searchUser,
                Param = param,
            };

            return View(model);
        }
    }
}

WebUI/Twitter.WebUI.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    @if (ViewBag.Description != null)
    {
        <meta name="description" content="@Html.Raw(ViewBag.Description)" />
    }
    @if (ViewBag.Robots != null)
    {
        <meta name="robots" content="@ViewBag.Robots" />
    }
    @if (ViewBag.Canonical != null)
    {
        <link rel="canonical" href="@Html.Raw(ViewBag.Canonical)/" />
    }
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="~/_assets/css/style.css" rel="stylesheet">
    <link href="~/_assets/css/icomoon.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,700&display=swap&subset=latin-ext" rel="stylesheet">
</head>
<body>

    <div class="x-hd">
        <div class="container">
            <span class="icon-menu"></span>
            <header>
                <a title="@CacheHelper.Setting.Sitename online twitter viewer" href="/">
                    <img src="~/_assets/img/logo.png" style="border-radius:50%;" width="50" height="50" 
                         alt="@CacheHelper.Setting.Sitename online twitter viewer" 
                         title="@CacheHelper.Setting.Sitename online twitter viewer"
                    />
                    <strong style="height: 40px; line-height: 50px;">@CacheHelper.Setting.Sitename</strong>
                </a>
            </header>
            <nav>
                <ul>
                    <li>
                        <a title="Search and discover twitter accounts" href="@Url.Action("Index","Search")/">Search</a>
                    </li>
                    <li>
                        <a title="Discover popular twitter accounts list" href="@Url.Action("All","List")/">Lists</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    @RenderBody()

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <script>
        document.querySelector(".icon-menu").onclick = function () {
            var hdNav = document.querySelector(".x-hd nav");
            if (hdNav.style.display == "" || hdNav.style.display == "none")
                hdNav.style.display = "block";
            else {
                hdNav.style.display = "none";
            }
        }
    </script>

    @RenderSection("scripts", required: false)
    @RenderSection("styles", required: false)

</body>
</html>