WebUI/Twitter.WebUI.Site/Models/HomeViewModel.cs
namespace Twitter.WebUI.Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    public class HomeViewModel
    {
        public HomeViewModel()
        {
            Lists = new List<Model.List>();
            PopularUsers = new List<Model.PopularUser>();
            Hashtags = new List<Model.Hashtag>();
        }

        public List<Model.List> Lists { get; set; }
        public List<Model.PopularUser> PopularUsers { get; set; }
        public List<Model.Hashtag> Hashtags { get; set; }
    }
}

WebUI/Twitter.WebUI.Site/Controllers/HashtagController.cs
namespace Twitter.WebUI.Site.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Twitter.Api;
    using Twitter.Data;
    using Twitter.WebUI.Site.Models;

    public class HashtagController : Controller
    {
        AuthUserData _userData;
        TokenData _tokenData;
        PopularUserData _popularUserData;

        public HashtagController()
        {
            _userData = new AuthUserData();
            _tokenData = new TokenData();
            _popularUserData = new PopularUserData();
        }

        public ActionResult Index(string hashtag)
        {
            if (string.IsNullOrEmpty(hashtag))
                return RedirectToAction("Index", "Home", new { q = "hashtag-is-empty" });

            Random rnd = new Random();
            var userById = _userData.GetBy(x => x.IsActive).OrderBy(x => rnd.Next()).FirstOrDefault();
            var token = _tokenData.GetByKey(userById.TokenId);

            var info = new Gatherer(token.ConsumerKey, token.ConsumerSecret, userById.OAuthToken, userById.OAuthTokenSecret);

            var hashtagResult = info.GetStatusesByTag(hashtag);

            var tags = new HashtagData().GetAll().OrderBy(x => rnd.Next()).Take(15).ToList();

            var model = new HashtagViewModoel()
            {
                Hashtags = hashtagResult,
                TrendHashtags = tags,
            };

            return View(model);
        }
    }
}

WebUI/Twitter.WebUI.Site/Controllers/HomeController.cs
namespace Twitter.WebUI.Site.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Twitter.Data;
    using Twitter.WebUI.Site.Helpers;
    using Twitter.WebUI.Site.Models;

    public class HomeController : Controller
    {
        ListData _listData;
        PopularUserData _popularUserData;
        HashtagData _hashtagData;

        public HomeController()
        {
            _listData = new ListData();
            _popularUserData = new PopularUserData();
            _hashtagData = new HashtagData();
        }

        public ActionResult Index()
        {
            Random rnd = new Random();
            var list = _listData.GetAll().OrderBy(x => rnd.Next()).Take(8).ToList();
            var users = _popularUserData.GetBy(x => x.IsActive).OrderBy(x => rnd.Next()).Take(15).ToList();
            var hashtags = _hashtagData.GetBy(x => x.IsActive).OrderBy(x => rnd.Next()).Take(9).ToList();


            var model = new HomeViewModel()
            {
                Lists = list,
                PopularUsers = users,
                Hashtags = hashtags,
            };

            return View(model);
        }

        public ActionResult ClearCache()
        {
            CacheHelper.ClearCaches();
            return RedirectToAction("Index", new { q = "reload-cache" });
        }
    }
}

WebUI/Twitter.WebUI.Site/Controllers/PopularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Twitter.Data;
using Twitter.WebUI.Site.Models;

namespace Twitter.WebUI.Site.Controllers
{
    public class PopularController : Controller
    {
        ListData _listData;
        PopularUserData _popularUserData;

        public PopularController()
        {
            _listData = new ListData();
            _popularUserData = new PopularUserData();
        }

        public ActionResult Index(int page = 1)
        {
            var users = _popularUserData.GetByPage(x => x.IsActive, page, 102, "FollowerCount", true);
            var count = _popularUserData.GetCount();

            int total = count / 102;
            total = total + 1;
            var model = new PopularViewModel()
            {
                PopularUsers = users,
                Page = page,
                TotalCount = count,
                TotalPage = total,
            };

            return View(model);
        }

    }
}

WebUI/Twitter.WebUI.Site/Controllers/SearchController.cs
namespace Twitter.WebUI.Site.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Twitter.Api;
    using Twitter.Data;
    using Twitter.WebUI.Site.Models;

    public class SearchController : Controller
    {
        AuthUserData _userData;
        TokenData _tokenData;
        PopularUserData _popularUserData;

        public SearchController()
        {
            _userData = new AuthUserData();
            _tokenData = new TokenData();
            _popularUserData = new PopularUserData();
        }

        public ActionResult Index(string param)
        {
            var model = new SearchViewModel();

            if (string.IsNullOrEmpty(param))
                return View(model);

            Random rnd = new Random();
            var userById = _userData.GetBy(x => x.IsActive).OrderBy(x => rnd.Next()).FirstOrDefault();
            var token = _tokenData.GetByKey(userById.TokenId);

            var info = new Gatherer(token.ConsumerKey, token.ConsumerSecret, userById.OAuthToken, userById.OAuthTokenSecret);

            var searchUser = info.GetUsersSearch(param);

            if (searchUser.Users.Count() <= 0)
            {
                model.Populars = _popularUserData.GetBy(x => x.IsActive).OrderBy(x => rnd.Next()).Take(20).ToList();
            }

            model = new SearchViewModel()
            {
                Users = searchUser,
                Param = param,
            };

            return View(model);
        }
    }
}

WebUI/Twitter.WebUI.Site/Views/Home/Index.cshtml
@model HomeViewModel
@{
    ViewBag.Title = "Online Twitter Viewer";
    ViewBag.Description = "Twitter tweets, friends, followers and statistics is on the web with a new design experience in website";
    ViewBag.Robots = "index,follow";
    ViewBag.Canonical = Url.Action("Index", "Home");
}

<section class="x-home-section gradient-light--lean-right">
    <div class="container">
        <figure class="figure highlight-background highlight-background--lean-right">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1291px" height="480px">
                <defs>
                    <linearGradient id="PSgrad_0" x1="0%" x2="0%" y1="100%" y2="0%">
                        <stop offset="28%" stop-color="rgb(244,245,250)" stop-opacity="1"></stop>
                        <stop offset="100%" stop-color="rgb(252,253,255)" stop-opacity="1"></stop>
                    </linearGradient>
                </defs>
                <path fill-rule="evenodd" opacity="0.1" fill="rgb(0, 0, 0)" d="M480.084,0.001 L1290.991,0.001 L810.906,831.000 L-0.000,831.000 L480.084,0.001 Z"></path>
                <path fill="url(#PSgrad_0)" d="M480.084,0.001 L1290.991,0.001 L810.906,831.000 L-0.000,831.000 L480.084,0.001 Z"></path>
            </svg>
        </figure>

        <div class="row vh-100">

            <div class="col-md-8 offset-md-2 col-lg-5 offset-lg-0 align-self-center text-center text-lg-left">

                <h1 class="mb-3 x-home-title">Become Social Media Marketing Experts</h1>

                <p class="x-home-lead mb-5">We makes it easy for businesses and marketing teams to manage your social account in a single place.</p>

                <a href="@Url.Action("Index","Search")/" class="btn btn-primary x-home-button">Search Now</a>

            </div>

            <div class="d-none d-lg-block col-lg-7 align-self-end text-right">
                <img src="~/_assets/img/hero_image.png" alt="Fluxo Social Media Marketing Template" class="mw-100">
            </div>

        </div>
    </div>
</section>

<section class="x-features mb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3 text-center">
                <h3 class="x-block-title">Save time managing social media for your business</h3>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12 text-center">
                <div class="x-icon">
                    <i class="icon-search4"></i>
                </div>
                <p class="x-feat-title">Influencer</p>
                <p class="x-feat-summary">Easy made twitter influencer discovered popular account and find all twitter accounts</p>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12 text-center">
                <div class="x-icon">
                    <i class="icon-person"></i>
                </div>
                <p class="x-feat-title">Friends & Followers</p>
                <p class="x-feat-summary">Easy looking twitter followers and friends. Twitter account followers and frineds lists</p>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12 text-center">
                <div class="x-icon">
                    <i class="icon-chart"></i>
                </div>
                <p class="x-feat-title">Account Statistics</p>
                <p class="x-feat-summary">Historical made twitter account statistics easy make daily change statistics follow any accounts</p>
            </div>
        </div>
    </div>
</section>

<section class="my-5">
    <div class="container">
        <div class="row py-5">
            <div class="col-md-5 pt-5 text-center">
                <h3 class="x-block-title">Why you should Join Event</h3>
                <p class="mb-4">How you transform your business as tech, consumer, habits industry dynamic change, Find out from those leading the charge.</p>
                <a href="@Url.Action("Index","Popular")/" class="btn btn-primary x-home-button">Discover Accounts</a>
            </div>
            <div class="col-md-7">
                <div class="row">
                    <div class="col-md-6">
                        <div class="x-popular-block">
                            <strong>Popular Account</strong>
                            <p>+1 Milion followers accounts</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="x-popular-block">
                            <strong>Most Followed</strong>
                            <p>Must followed twitter popular accounts</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="x-popular-block">
                            <strong>Celebrity Account</strong>
                            <p>Discover twitter celebrity accounts</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="x-popular-block">
                            <strong>Popular List</strong>
                            <p>List of twitter accounts, sortable with followers count</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<div class="container populars">
    <h3 class="text-center mb-4 x-block-title">Popular Twitter Accounts</h3>
    <div class="row">
        @{ var counter = 0;}
        @foreach (var item in Model.PopularUsers)
        {
            var fullanme = string.IsNullOrEmpty(item.Fullname) ? item.Username : item.Fullname;
            counter++;
            <div class="col-xs-12 col-sm-6 col-lg-4 mb-3">
                <div class="row">
                    <div class="col-xs-4">
                        <a href="@Url.Action("Index","Account", new { username = item.Username })/" title="@SeoHelper.UserHrefText(item.Username,item.Fullname)">
                            <img class="rounded-circle mr-2" width="150" height="150" 
                                 src=""
                                 lazy-src="@item.ImagePath"
                                 onerror="this.src='/_assets/img/default.png'"
                                 alt="@SeoHelper.UserImageAlt(item.Username, fullanme)" 
                                 title="@SeoHelper.UserImageAlt(item.Username, fullanme)"
                            />
                        </a>
                    </div>
                    <div class="col-xs-8">
                        <p class="mb-0">
                            <a href="@Url.Action("Index","Account", new { username = item.Username })/" title="@SeoHelper.UserHrefText(item.Username,item.Fullname)">
                                <span class="badge badge-secondary">@counter</span> @fullanme
                            </a>
                        </p>
                        <p class="mb-2"><span>@UIHelper.ToCommaSeparetadNumber(item.TweetCount)</span> Tweets</p>
                        <p class="mb-2"><span>@UIHelper.ToCommaSeparetadNumber(item.FriendCount)</span> Followings</p>
                        <p class="mb-2"><span>@UIHelper.ToCommaSeparetadNumber(item.FollowerCount)</span> Followers</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<<<<<<< HEAD
<div class="hashtag-bg"></div>
<div class="container">
    <h3 class="text-center mb-4 x-block-title">Popular Twitter Hashtags</h3>
    <div class="row">
        @foreach (var item in Model.Hashtags)
        {
            <div class="col-xs-12 col-sm-6 col-lg-3 mb-5" style="text-align: center; height: 90px; display: flex; justify-content: center; align-items: center;">
                <a href="@Url.Action("Index","Hashtag", new { hashtag = item.Name.ToLower() })/" title="@SeoHelper.HastagHrefText(item.Name)" style=" background: #fff; padding: 20px; border-radius: 50%; height:110px; width: 110px;">
                    <i class="@item.Icon" style="font-size:50px;"></i>
                    <p>@item.Name</p>
                </a>
            </div>
        }
=======
<div class="hashtag-bg">
    <div class="container">
        <h3 class="text-center mb-4 x-block-title">Popular Twitter Hashtags</h3>
        <div class="row">
            @foreach (var item in Model.Hashtags)
            {
                <div class="col-xs-12 col-sm-6 col-lg-4 mb-3">
                    <a href="@Url.Action("Index","Hashtag", new { hashtag = item.Name.ToLower() })/" title="@SeoHelper.HastagHrefText(item.Name)">
                        <i class="@item.Icon"></i>
                        <p>@item.Name</p>
                    </a>
                </div>
            }
        </div>
>>>>>>> 5f76db5f1e38dddca485ba0a1353359e6634383a
    </div>
</div>


@section scripts{
    <script>
        $('body').on("keypress", "input[name='HomeSearch']", SearchWithEnter);
        $("body").on("click", "button[name='SearchBtn']", SearchUser);

        function clearForSearch(value) {
            value = value.replace('#', '');
            value = value.replace('<', '');
            value = value.replace('>', '');
            value = value.replace('%', '');
            value = value.replace('&', '');
            value = value.replace('.', '');
            value = value.replace('*', '');
            value = value.replace('/', '');
            value = value.replace('~', '');
            value = value.replace(';', '');
            value = value.replace('@@', '');
            return value;
        }

        function SearchWithEnter(event) {
            var keycode = (event.originalEvent.keyCode ? event.originalEvent.keyCode : event.originalEvent.which);
            if (keycode === 13) {
                var text = $("input[name='HomeSearch']").val();
                text = clearForSearch(text);
                if (text.length > 2) {
                    window.location.href = "/search/" + text + "/";
                }
                else {
                    alert("text too short min 3");
                }
            }
        }

        function SearchUser() {
            var text = $("input[name='HomeSearch']").val();
            text = clearForSearch(text);
            if (text.length > 2) {
                window.location.href = "/search/" + text + "/";
            }
            else {
                alert("text too short min 3");
            }
        }

        var intersectionObserverExists = 'IntersectionObserver' in window;
        if (intersectionObserverExists) {
            var callback = function (entries, observer) {
                entries.forEach(entry => {
                    if (entry.isIntersecting) {
                        var dataSrc = entry.target.getAttribute('lazy-src');
                        if (dataSrc == null || dataSrc == undefined) {
                            return;
                        }
                        if (dataSrc != '') {
                            entry.target.setAttribute('src', dataSrc);
                            entry.target.setAttribute('lazy-src', '');
                        }
                    }
                });
            };
            var options = {
                root: null,
                rootMargin: '0px',
                threshold: 0.01
            };

            var observer = new IntersectionObserver(callback, options);
            var images = document.querySelectorAll('.populars img');
            images.forEach(img => observer.observe(img));
        }
    </script>
}